#define PROJECT_NAME "Thermal-EX"
#define PROJECT_VERSION "2.2.12"
#define PROJECT_DESCRIPTION "Ultrasonic-HCSR04, LED"
#define PROJECT_VERSION_MAJOR 2
#define PROJECT_VERSION_MINOR 2
#define PROJECT_VERSION_PATCH 12
