#define PROJECT_NAME "Thermal-EX"
#define PROJECT_VERSION "2.1.1"
#define PROJECT_DESCRIPTION "Ultrasonic-HCSR04, LED"
#define PROJECT_VERSION_MAJOR 2
#define PROJECT_VERSION_MINOR 1
#define PROJECT_VERSION_PATCH 1
